const ERROR_INTERNAL_SERVER = 500;
const ERROR_BAD_REQUEST = 400;
const ERROR_NOT_FOUND = 404;
const STATUS_CREATED = 201;

module.exports = {
  ERROR_INTERNAL_SERVER,
  ERROR_BAD_REQUEST,
  ERROR_NOT_FOUND,
  STATUS_CREATED,
};
